version: '3'
services:
  web:
    image: nginx:1.23
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf.docker:/etc/nginx/conf.d/default.conf
  app:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app